// Code generated by "stringer -type=PlugectOpcode,HostOpcode -output=opcode_string.go"; DO NOT EDIT.

package vst2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[plugOpen-0]
	_ = x[plugClose-1]
	_ = x[plugSetProgram-2]
	_ = x[plugGetProgram-3]
	_ = x[plugSetProgramName-4]
	_ = x[plugGetProgramName-5]
	_ = x[plugGetParamLabel-6]
	_ = x[plugGetParamDisplay-7]
	_ = x[plugGetParamName-8]
	_ = x[plugGetVu-9]
	_ = x[plugSetSampleRate-10]
	_ = x[plugSetBufferSize-11]
	_ = x[plugStateChanged-12]
	_ = x[PlugEditGetRect-13]
	_ = x[PlugEditOpen-14]
	_ = x[PlugEditClose-15]
	_ = x[plugEditDraw-16]
	_ = x[plugEditMouse-17]
	_ = x[plugEditKey-18]
	_ = x[PlugEditIdle-19]
	_ = x[plugEditTop-20]
	_ = x[plugEditSleep-21]
	_ = x[plugIdentify-22]
	_ = x[plugGetChunk-23]
	_ = x[plugSetChunk-24]
	_ = x[PlugProcessEvents-25]
	_ = x[PlugCanBeAutomated-26]
	_ = x[PlugString2Parameter-27]
	_ = x[plugGetNumProgramCategories-28]
	_ = x[plugGetProgramNameIndexed-29]
	_ = x[plugCopyProgram-30]
	_ = x[plugConnectInput-31]
	_ = x[plugConnectOutput-32]
	_ = x[PlugGetInputProperties-33]
	_ = x[PlugGetOutputProperties-34]
	_ = x[PlugGetPlugCategory-35]
	_ = x[plugGetCurrentPosition-36]
	_ = x[plugGetDestinationBuffer-37]
	_ = x[PlugOfflineNotify-38]
	_ = x[PlugOfflinePrepare-39]
	_ = x[PlugOfflineRun-40]
	_ = x[PlugProcessVarIo-41]
	_ = x[plugSetSpeakerArrangement-42]
	_ = x[plugSetBlockSizeAndSampleRate-43]
	_ = x[PlugSetBypass-44]
	_ = x[PlugGetPluginName-45]
	_ = x[plugGetErrorText-46]
	_ = x[PlugGetVendorString-47]
	_ = x[PlugGetProductString-48]
	_ = x[PlugGetVendorVersion-49]
	_ = x[PlugVendorSpecific-50]
	_ = x[PlugCanDo-51]
	_ = x[PlugGetTailSize-52]
	_ = x[plugIdle-53]
	_ = x[plugGetIcon-54]
	_ = x[plugSetViewPosition-55]
	_ = x[plugGetParameterProperties-56]
	_ = x[plugKeysRequired-57]
	_ = x[PlugGetVstVersion-58]
	_ = x[PlugEditKeyDown-59]
	_ = x[PlugEditKeyUp-60]
	_ = x[PlugSetEditKnobMode-61]
	_ = x[PlugGetMidiProgramName-62]
	_ = x[PlugGetCurrentMidiProgram-63]
	_ = x[PlugGetMidiProgramCategory-64]
	_ = x[PlugHasMidiProgramsChanged-65]
	_ = x[PlugGetMidiKeyName-66]
	_ = x[PlugBeginSetProgram-67]
	_ = x[PlugEndSetProgram-68]
	_ = x[PlugGetSpeakerArrangement-69]
	_ = x[PlugShellGetNextPlugin-70]
	_ = x[PlugStartProcess-71]
	_ = x[PlugStopProcess-72]
	_ = x[PlugSetTotalSampleToProcess-73]
	_ = x[PlugSetPanLaw-74]
	_ = x[PlugBeginLoadBank-75]
	_ = x[PlugBeginLoadProgram-76]
	_ = x[PlugSetProcessPrecision-77]
	_ = x[PlugGetNumMidiInputChannels-78]
	_ = x[PlugGetNumMidiOutputChannels-79]
}

const _PlugectOpcode_name = "PlugOpenPlugClosePlugSetProgramPlugGetProgramPlugSetProgramNamePlugGetProgramNamePlugGetParamLabelPlugGetParamDisplayPlugGetParamNameplugGetVuPlugSetSampleRatePlugSetBufferSizePlugStateChangedPlugEditGetRectPlugEditOpenPlugEditCloseplugEditDrawplugEditMouseplugEditKeyPlugEditIdleplugEditTopplugEditSleepplugIdentifyPlugGetChunkPlugSetChunkPlugProcessEventsPlugCanBeAutomatedPlugString2ParameterplugGetNumProgramCategoriesPlugGetProgramNameIndexedplugCopyProgramplugConnectInputplugConnectOutputPlugGetInputPropertiesPlugGetOutputPropertiesPlugGetPlugCategoryplugGetCurrentPositionplugGetDestinationBufferPlugOfflineNotifyPlugOfflinePreparePlugOfflineRunPlugProcessVarIoPlugSetSpeakerArrangementplugSetBlockSizeAndSampleRatePlugSetBypassPlugGetPlugectNameplugGetErrorTextPlugGetVendorStringPlugGetProductStringPlugGetVendorVersionPlugVendorSpecificPlugCanDoPlugGetTailSizeplugIdleplugGetIconplugSetViewPositionPlugGetParameterPropertiesplugKeysRequiredPlugGetVstVersionPlugEditKeyDownPlugEditKeyUpPlugSetEditKnobModePlugGetMidiProgramNamePlugGetCurrentMidiProgramPlugGetMidiProgramCategoryPlugHasMidiProgramsChangedPlugGetMidiKeyNamePlugBeginSetProgramPlugEndSetProgramPlugGetSpeakerArrangementPlugShellGetNextPluginPlugStartProcessPlugStopProcessPlugSetTotalSampleToProcessPlugSetPanLawPlugBeginLoadBankPlugBeginLoadProgramPlugSetProcessPrecisionPlugGetNumMidiInputChannelsPlugGetNumMidiOutputChannels"

var _PlugectOpcode_index = [...]uint16{0, 7, 15, 28, 41, 58, 75, 91, 109, 124, 132, 148, 164, 179, 193, 204, 216, 227, 239, 249, 260, 270, 282, 293, 304, 315, 331, 348, 367, 393, 417, 431, 446, 462, 483, 505, 523, 544, 567, 583, 600, 613, 628, 652, 680, 692, 708, 723, 741, 760, 779, 796, 804, 818, 825, 835, 853, 878, 893, 909, 923, 935, 953, 974, 998, 1023, 1048, 1065, 1083, 1099, 1123, 1144, 1159, 1173, 1199, 1211, 1227, 1246, 1268, 1294, 1321}

func (i PluginOpcode) String() string {
	if i >= PluginOpcode(len(_PlugectOpcode_index)-1) {
		return "PlugectOpcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlugectOpcode_name[_PlugectOpcode_index[i]:_PlugectOpcode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HostAutomate-0]
	_ = x[HostVersion-1]
	_ = x[HostCurrentID-2]
	_ = x[HostIdle-3]
	_ = x[hostPinConnected-4]
	_ = x[hostWantMidi-6]
	_ = x[HostGetTime-7]
	_ = x[HostProcessEvents-8]
	_ = x[hostSetTime-9]
	_ = x[hostTempoAt-10]
	_ = x[hostGetNumAutomatableParameters-11]
	_ = x[hostGetParameterQuantization-12]
	_ = x[HostIOChanged-13]
	_ = x[hostNeedIdle-14]
	_ = x[HostSizeWindow-15]
	_ = x[HostGetSampleRate-16]
	_ = x[HostGetBlockSize-17]
	_ = x[HostGetInputLatency-18]
	_ = x[HostGetOutputLatency-19]
	_ = x[hostGetPreviousPlug-20]
	_ = x[hostGetNextPlug-21]
	_ = x[hostWillReplaceOrAccumulate-22]
	_ = x[HostGetCurrentProcessLevel-23]
	_ = x[HostGetAutomationState-24]
	_ = x[HostOfflineStart-25]
	_ = x[HostOfflineRead-26]
	_ = x[HostOfflineWrite-27]
	_ = x[HostOfflineGetCurrentPass-28]
	_ = x[HostOfflineGetCurrentMetaPass-29]
	_ = x[hostSetOutputSampleRate-30]
	_ = x[hostGetOutputSpeakerArrangement-31]
	_ = x[HostGetVendorString-32]
	_ = x[HostGetProductString-33]
	_ = x[HostGetVendorVersion-34]
	_ = x[HostVendorSpecific-35]
	_ = x[hostSetIcon-36]
	_ = x[HostCanDo-37]
	_ = x[HostGetLanguage-38]
	_ = x[hostOpenWindow-39]
	_ = x[hostCloseWindow-40]
	_ = x[HostGetDirectory-41]
	_ = x[HostUpdateDisplay-42]
	_ = x[HostBeginEdit-43]
	_ = x[HostEndEdit-44]
	_ = x[HostOpenFileSelector-45]
	_ = x[HostCloseFileSelector-46]
	_ = x[hostEditFile-47]
	_ = x[hostGetChunkFile-48]
	_ = x[hostGetInputSpeakerArrangement-49]
}

const (
	_HostOpcode_name_0 = "HostAutomateHostVersionHostCurrentIDHostIdlehostPinConnected"
	_HostOpcode_name_1 = "hostWantMidiHostGetTimeHostProcessEventshostSetTimehostTempoAthostGetNumAutomatableParametershostGetParameterQuantizationHostIOChangedhostNeedIdleHostSizeWindowHostGetSampleRateHostGetBlockSizeHostGetInputLatencyHostGetOutputLatencyhostGetPreviousPlughostGetNextPlughostWillReplaceOrAccumulateHostGetCurrentProcessLevelHostGetAutomationStateHostOfflineStartHostOfflineReadHostOfflineWriteHostOfflineGetCurrentPassHostOfflineGetCurrentMetaPasshostSetOutputSampleRatehostGetOutputSpeakerArrangementHostGetVendorStringHostGetProductStringHostGetVendorVersionHostVendorSpecifichostSetIconHostCanDoHostGetLanguagehostOpenWindowhostCloseWindowHostGetDirectoryHostUpdateDisplayHostBeginEditHostEndEditHostOpenFileSelectorHostCloseFileSelectorhostEditFilehostGetChunkFilehostGetInputSpeakerArrangement"
)

var (
	_HostOpcode_index_0 = [...]uint8{0, 12, 23, 36, 44, 60}
	_HostOpcode_index_1 = [...]uint16{0, 12, 23, 40, 51, 62, 93, 121, 134, 146, 160, 177, 193, 212, 232, 251, 266, 293, 319, 341, 357, 372, 388, 413, 442, 465, 496, 515, 535, 555, 573, 584, 593, 608, 622, 637, 653, 670, 683, 694, 714, 735, 747, 763, 793}
)

func (i HostOpcode) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _HostOpcode_name_0[_HostOpcode_index_0[i]:_HostOpcode_index_0[i+1]]
	case 6 <= i && i <= 49:
		i -= 6
		return _HostOpcode_name_1[_HostOpcode_index_1[i]:_HostOpcode_index_1[i+1]]
	default:
		return "HostOpcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
